import type { Lang } from "@/lib/useLang";

// Every word of the creator app, in both languages. Creators are addressed
// with "tu" in French, like most creator platforms.

export type MissionStage = "invited" | "accepted" | "signed" | "shipped" | "delivered" | "submitted" | "changes" | "approved" | "declined";
export type SlotStatus = "empty" | "pending" | "changes_requested" | "approved";

const EN = {
  tabs: { home: "Home", missions: "Missions", earnings: "Earnings", profile: "Profile" },
  hello: (name: string) => (name ? `Hi ${name}` : "Hi there"),
  missionsOngoing: (n: number) => (n === 0 ? "No mission in progress" : n === 1 ? "1 mission in progress" : `${n} missions in progress`),
  sampleNote: "Local preview: sample data.",
  myBrands: "My brands",
  allBrands: "All my brands",
  brandsCount: (n: number) => (n === 1 ? "1 brand" : `${n} brands`),
  noBrands: "No brand yet. When a brand invites you, it shows up here.",
  model: { commission: "Commission", rpm: "RPM", gifting: "Gifting" },
  rateCommission: (r: number) => `${r} % per sale`,
  rateRpm: (money: string) => `${money} / 1,000 views`,
  giftingOnly: "Gifting: the product in exchange for your content.",
  // Commission
  commissionTitle: "Your commissions",
  toReceive: "to receive",
  earnedTotal: (total: string, sales: number) => `${total} earned in total · ${sales} ${sales === 1 ? "sale" : "sales"}`,
  // RPM
  rpmTitle: "Your view earnings",
  rpmLine: (views: string, videos: number) => `${views} views · ${videos} ${videos === 1 ? "video" : "videos"}`,
  pendingViews: (money: string) => `${money} being counted`,
  addPayout: "Add your PayPal, Revolut or IBAN to get paid",
  yourCode: "Your code",
  yourLink: "Your link",
  missionTitle: "Your mission right now",
  noMission: "No mission yet",
  noMissionText: "When a brand sends you a product, the mission shows up here. You'll have one button to press at each step.",
  dueBy: (date: string) => `Due by ${date}`,
  step: (i: number, n: number) => `Step ${i}/${n}`,
  contentsProgress: (done: number, total: number) => `${done}/${total} ${total === 1 ? "content" : "contents"} sent`,
  stages: {
    invited: "Invitation received",
    accepted: "Contract to sign",
    signed: "The brand is preparing your parcel",
    shipped: "Your parcel is on the way",
    delivered: "Your content is expected",
    submitted: "Content in review",
    changes: "The brand asks for a change",
    approved: "Content approved",
    declined: "Mission declined",
  } satisfies Record<MissionStage, string>,
  cta: {
    invited: "See the invitation",
    accepted: "Sign and give my address",
    shipped: "I received the parcel",
    delivered: "Send my content",
    changes: "Fix my content",
    waiting: "See the mission",
  },
  waitingNote: {
    signed: "Nothing to do: the brand ships soon.",
    submitted: "Nothing to do: the brand is reviewing your content.",
    approved: "Well done. This mission is complete.",
  },
  latestSales: "My latest sales",
  noSales: "No sale yet. Share your code or link to earn your first commission.",
  commission: "commission",
  missionsTitle: "My missions",
  missionsEmpty: "No mission yet. Brands invite you here.",
  stepsLabels: ["Invitation", "Contract", "Parcel", "Content", "Approved"],
  brief: "Brief",
  readContract: "Read the contract",
  accept: "Accept the mission",
  decline: "Decline",
  declineConfirm: "Decline this mission? The brand will be told.",
  fullName: "First and last name",
  street: "Street and number",
  postalCode: "Postal code",
  city: "City",
  country: "Country",
  consent: "I sign this contract, including the ad rights it mentions. The text stays frozen.",
  sign: "Sign the contract",
  deliveredConfirm: "Confirm you received the parcel?",
  contentTitle: "Send your content",
  contentText: (n: number) => (n === 1 ? "The brand expects 1 content (video or photo)." : `The brand expects ${n} contents (videos or photos).`),
  slot: (i: number) => `Content ${i}`,
  slotStatus: {
    empty: "To send",
    pending: "In review",
    changes_requested: "To redo",
    approved: "Approved",
  } satisfies Record<SlotStatus, string>,
  chooseFile: "Choose a video or a photo",
  replaceFile: "Send a new version",
  formats: "Video MP4, MOV, WebM up to 500 MB · Photo JPG, PNG, WebP up to 25 MB",
  send: "Send",
  sending: (p: number) => `Sending… ${p} %`,
  brandFeedback: "Brand's note",
  close: "Close",
  earningsTab: "Earnings",
  totalEarned: "Earned in total",
  salesCount: "Sales",
  views: "Views",
  videos: "Videos",
  perThousand: "per 1,000 views",
  rate: "Rate",
  payoutTitle: "How you get paid",
  payoutText: "Brands pay your commissions and view earnings here. Only they see it.",
  method: "Method",
  paypalPlaceholder: "paypal.me/username",
  revolutPlaceholder: "revolut.me/username",
  ibanPlaceholder: "FR76 …",
  holder: "Account holder",
  bank: "Bank",
  save: "Save",
  saved: "Saved",
  saveError: "Could not save. Try again.",
  noMoney: "Your brands work with you in gifting: no money to show here.",
  language: "Language",
  signOut: "Sign out",
  loadError: "Could not load your space. Check your connection.",
  retry: "Try again",
  actionError: "That did not work. Try again.",
  fileTooBig: "This file is too large.",
  fileType: "Send a video (MP4, MOV, WebM) or a photo (JPG, PNG, WebP).",
};

type Copy = typeof EN;

const FR: Copy = {
  tabs: { home: "Accueil", missions: "Missions", earnings: "Gains", profile: "Profil" },
  hello: (name) => (name ? `Salut ${name}` : "Salut"),
  missionsOngoing: (n) => (n === 0 ? "Aucune mission en cours" : n === 1 ? "1 mission en cours" : `${n} missions en cours`),
  sampleNote: "Aperçu local : données d’exemple.",
  myBrands: "Mes marques",
  allBrands: "Toutes mes marques",
  brandsCount: (n) => (n > 1 ? `${n} marques` : `${n} marque`),
  noBrands: "Pas encore de marque. Quand une marque t’invite, elle apparaît ici.",
  model: { commission: "Commission", rpm: "RPM", gifting: "Gifting" },
  rateCommission: (r) => `${r} % par vente`,
  rateRpm: (money) => `${money} / 1 000 vues`,
  giftingOnly: "Gifting : le produit en échange de ton contenu.",
  commissionTitle: "Tes commissions",
  toReceive: "à recevoir",
  earnedTotal: (total, sales) => `${total} gagnés au total · ${sales} ${sales > 1 ? "ventes" : "vente"}`,
  rpmTitle: "Tes gains aux vues",
  rpmLine: (views, videos) => `${views} vues · ${videos} ${videos > 1 ? "vidéos" : "vidéo"}`,
  pendingViews: (money) => `${money} en cours de calcul`,
  addPayout: "Ajoute ton PayPal, Revolut ou IBAN pour être payé",
  yourCode: "Ton code",
  yourLink: "Ton lien",
  missionTitle: "Ta mission du moment",
  noMission: "Pas encore de mission",
  noMissionText: "Quand une marque t’envoie un produit, la mission apparaît ici. À chaque étape, tu n’as qu’un bouton à toucher.",
  dueBy: (date) => `À rendre avant le ${date}`,
  step: (i, n) => `Étape ${i}/${n}`,
  contentsProgress: (done, total) => `${done}/${total} ${total > 1 ? "contenus envoyés" : "contenu envoyé"}`,
  stages: {
    invited: "Invitation reçue",
    accepted: "Contrat à signer",
    signed: "La marque prépare ton colis",
    shipped: "Ton colis est en route",
    delivered: "Ton contenu est attendu",
    submitted: "Contenu en revue",
    changes: "La marque demande une modification",
    approved: "Contenu validé",
    declined: "Mission refusée",
  },
  cta: {
    invited: "Voir l’invitation",
    accepted: "Signer et donner mon adresse",
    shipped: "J’ai reçu le colis",
    delivered: "Envoyer mon contenu",
    changes: "Corriger mon contenu",
    waiting: "Voir la mission",
  },
  waitingNote: {
    signed: "Rien à faire : la marque expédie bientôt.",
    submitted: "Rien à faire : la marque regarde ton contenu.",
    approved: "Bravo, cette mission est terminée.",
  },
  latestSales: "Mes dernières ventes",
  noSales: "Pas encore de vente. Partage ton code ou ton lien pour toucher ta première commission.",
  commission: "commission",
  missionsTitle: "Mes missions",
  missionsEmpty: "Pas encore de mission. Les marques t’invitent ici.",
  stepsLabels: ["Invitation", "Contrat", "Colis", "Contenu", "Validé"],
  brief: "Brief",
  readContract: "Lire le contrat",
  accept: "Accepter la mission",
  decline: "Refuser",
  declineConfirm: "Refuser cette mission ? La marque sera prévenue.",
  fullName: "Prénom et nom",
  street: "Numéro et rue",
  postalCode: "Code postal",
  city: "Ville",
  country: "Pays",
  consent: "Je signe ce contrat, y compris les droits publicitaires qu’il mentionne. Le texte reste figé.",
  sign: "Signer le contrat",
  deliveredConfirm: "Tu confirmes avoir reçu le colis ?",
  contentTitle: "Envoie ton contenu",
  contentText: (n) => (n > 1 ? `La marque attend ${n} contenus (vidéos ou photos).` : "La marque attend 1 contenu (vidéo ou photo)."),
  slot: (i) => `Contenu ${i}`,
  slotStatus: {
    empty: "À envoyer",
    pending: "En revue",
    changes_requested: "À refaire",
    approved: "Validé",
  },
  chooseFile: "Choisir une vidéo ou une photo",
  replaceFile: "Envoyer une nouvelle version",
  formats: "Vidéo MP4, MOV, WebM jusqu’à 500 Mo · Photo JPG, PNG, WebP jusqu’à 25 Mo",
  send: "Envoyer",
  sending: (p) => `Envoi… ${p} %`,
  brandFeedback: "Mot de la marque",
  close: "Fermer",
  earningsTab: "Gains",
  totalEarned: "Gagné au total",
  salesCount: "Ventes",
  views: "Vues",
  videos: "Vidéos",
  perThousand: "pour 1 000 vues",
  rate: "Taux",
  payoutTitle: "Comment tu es payé",
  payoutText: "Les marques versent ici tes commissions et tes gains aux vues. Elles seules le voient.",
  method: "Moyen",
  paypalPlaceholder: "paypal.me/pseudo",
  revolutPlaceholder: "revolut.me/pseudo",
  ibanPlaceholder: "FR76 …",
  holder: "Titulaire du compte",
  bank: "Banque",
  save: "Enregistrer",
  saved: "Enregistré",
  saveError: "Enregistrement impossible. Réessaie.",
  noMoney: "Tes marques travaillent avec toi en gifting : pas d’argent à afficher ici.",
  language: "Langue",
  signOut: "Se déconnecter",
  loadError: "Impossible de charger ton espace. Vérifie ta connexion.",
  retry: "Réessayer",
  actionError: "Ça n’a pas marché. Réessaie.",
  fileTooBig: "Ce fichier est trop lourd.",
  fileType: "Envoie une vidéo (MP4, MOV, WebM) ou une photo (JPG, PNG, WebP).",
};

export function creatorCopy(lang: Lang): Copy {
  return lang === "fr" ? FR : EN;
}

export type CreatorCopy = Copy;
