import type { Lang } from "@/lib/useLang";

// Every word of the creator app, in both languages. Creators are addressed
// with "tu" in French, like most creator platforms.

export type MissionStage = "invited" | "accepted" | "signed" | "shipped" | "delivered" | "submitted" | "changes" | "approved" | "declined";

const EN = {
  tabs: { home: "Home", missions: "Missions", earnings: "Earnings", profile: "Profile" },
  hello: (name: string) => (name ? `Hi ${name}` : "Hi there"),
  missionsOngoing: (n: number) => (n === 0 ? "No mission in progress" : n === 1 ? "1 mission in progress" : `${n} missions in progress`),
  sample: "Sample",
  sampleNote: "Local preview: sample data.",
  earningsTitle: "Your earnings",
  toReceive: "to receive",
  earnedTotal: (total: string, sales: number) => `${total} earned in total · ${sales} ${sales === 1 ? "sale" : "sales"}`,
  noBrand: "No brand yet. When a brand adds you, your sales and commissions show up here.",
  addPayout: "Add your PayPal, Revolut or IBAN to get paid",
  yourCode: "Your code",
  yourLink: "Your link",
  copy: "Copy",
  copied: "Copied",
  missionTitle: "Your mission right now",
  noMission: "No mission yet",
  noMissionText: "When a brand sends you a product, the mission shows up here. You'll have one button to press at each step.",
  dueBy: (date: string) => `Video due by ${date}`,
  step: (i: number, n: number) => `Step ${i}/${n}`,
  stages: {
    invited: "Invitation received",
    accepted: "Contract to sign",
    signed: "The brand is preparing your parcel",
    shipped: "Your parcel is on the way",
    delivered: "Your video is expected",
    submitted: "Video in review",
    changes: "The brand asks for a change",
    approved: "Video approved",
    declined: "Mission declined",
  } satisfies Record<MissionStage, string>,
  cta: {
    invited: "See the invitation",
    accepted: "Sign and give my address",
    shipped: "I received the parcel",
    delivered: "Send my video",
    changes: "Send a new version",
    waiting: "See the mission",
  },
  waitingNote: {
    signed: "Nothing to do: the brand ships soon.",
    submitted: "Nothing to do: the brand is watching your video.",
    approved: "Well done. This mission is complete.",
  },
  latestSales: "My latest sales",
  noSales: "No sale yet. Share your code or link to earn your first commission.",
  commission: "commission",
  missionsTitle: "My missions",
  missionsEmpty: "No mission yet. Brands invite you here.",
  stepsLabels: ["Invitation", "Contract", "Parcel", "Video", "Approved"],
  product: "Product",
  brief: "Brief",
  readContract: "Read the contract",
  accept: "Accept the mission",
  decline: "Decline",
  declineConfirm: "Decline this mission? The brand will be told.",
  fullName: "First and last name",
  street: "Street and number",
  postalCode: "Postal code",
  city: "City",
  country: "Country",
  consent: "I sign this contract, including the ad rights it mentions. The text stays frozen.",
  sign: "Sign the contract",
  deliveredConfirm: "Confirm you received the parcel?",
  chooseVideo: "Choose my video",
  videoFormats: "MP4, MOV or WebM · 500 MB max",
  sendVideo: "Send the video",
  sending: (p: number) => `Sending… ${p} %`,
  brandFeedback: "Brand's note",
  close: "Close",
  earningsTab: "Earnings",
  totalEarned: "Earned in total",
  salesCount: "Sales",
  rate: "Commission",
  payoutTitle: "How you get paid",
  payoutText: "The brand pays your commissions here. Only the brand sees it.",
  method: "Method",
  paypalPlaceholder: "paypal.me/username",
  revolutPlaceholder: "revolut.me/username",
  ibanPlaceholder: "FR76 …",
  holder: "Account holder",
  bank: "Bank",
  save: "Save",
  saved: "Saved",
  saveError: "Could not save. Try again.",
  profileTitle: "Profile",
  language: "Language",
  legal: "Legal",
  signOut: "Sign out",
  loadError: "Could not load your space. Check your connection.",
  retry: "Try again",
  actionError: "That did not work. Try again.",
};

type Copy = typeof EN;

const FR: Copy = {
  tabs: { home: "Accueil", missions: "Missions", earnings: "Gains", profile: "Profil" },
  hello: (name) => (name ? `Salut ${name}` : "Salut"),
  missionsOngoing: (n) => (n === 0 ? "Aucune mission en cours" : n === 1 ? "1 mission en cours" : `${n} missions en cours`),
  sample: "Exemple",
  sampleNote: "Aperçu local : données d’exemple.",
  earningsTitle: "Tes gains",
  toReceive: "à recevoir",
  earnedTotal: (total, sales) => `${total} gagnés au total · ${sales} ${sales > 1 ? "ventes" : "vente"}`,
  noBrand: "Pas encore de marque. Quand une marque t’ajoute, tes ventes et commissions arrivent ici.",
  addPayout: "Ajoute ton PayPal, Revolut ou IBAN pour être payé",
  yourCode: "Ton code",
  yourLink: "Ton lien",
  copy: "Copier",
  copied: "Copié",
  missionTitle: "Ta mission du moment",
  noMission: "Pas encore de mission",
  noMissionText: "Quand une marque t’envoie un produit, la mission apparaît ici. À chaque étape, tu n’as qu’un bouton à toucher.",
  dueBy: (date) => `Vidéo à rendre avant le ${date}`,
  step: (i, n) => `Étape ${i}/${n}`,
  stages: {
    invited: "Invitation reçue",
    accepted: "Contrat à signer",
    signed: "La marque prépare ton colis",
    shipped: "Ton colis est en route",
    delivered: "Ta vidéo est attendue",
    submitted: "Vidéo en revue",
    changes: "La marque demande une modification",
    approved: "Vidéo validée",
    declined: "Mission refusée",
  },
  cta: {
    invited: "Voir l’invitation",
    accepted: "Signer et donner mon adresse",
    shipped: "J’ai reçu le colis",
    delivered: "Envoyer ma vidéo",
    changes: "Envoyer une nouvelle version",
    waiting: "Voir la mission",
  },
  waitingNote: {
    signed: "Rien à faire : la marque expédie bientôt.",
    submitted: "Rien à faire : la marque regarde ta vidéo.",
    approved: "Bravo, cette mission est terminée.",
  },
  latestSales: "Mes dernières ventes",
  noSales: "Pas encore de vente. Partage ton code ou ton lien pour toucher ta première commission.",
  commission: "commission",
  missionsTitle: "Mes missions",
  missionsEmpty: "Pas encore de mission. Les marques t’invitent ici.",
  stepsLabels: ["Invitation", "Contrat", "Colis", "Vidéo", "Validée"],
  product: "Produit",
  brief: "Brief",
  readContract: "Lire le contrat",
  accept: "Accepter la mission",
  decline: "Refuser",
  declineConfirm: "Refuser cette mission ? La marque sera prévenue.",
  fullName: "Prénom et nom",
  street: "Numéro et rue",
  postalCode: "Code postal",
  city: "Ville",
  country: "Pays",
  consent: "Je signe ce contrat, y compris les droits publicitaires qu’il mentionne. Le texte reste figé.",
  sign: "Signer le contrat",
  deliveredConfirm: "Tu confirmes avoir reçu le colis ?",
  chooseVideo: "Choisir ma vidéo",
  videoFormats: "MP4, MOV ou WebM · 500 Mo max",
  sendVideo: "Envoyer la vidéo",
  sending: (p) => `Envoi… ${p} %`,
  brandFeedback: "Mot de la marque",
  close: "Fermer",
  earningsTab: "Gains",
  totalEarned: "Gagné au total",
  salesCount: "Ventes",
  rate: "Commission",
  payoutTitle: "Comment tu es payé",
  payoutText: "La marque verse tes commissions ici. Elle seule le voit.",
  method: "Moyen",
  paypalPlaceholder: "paypal.me/pseudo",
  revolutPlaceholder: "revolut.me/pseudo",
  ibanPlaceholder: "FR76 …",
  holder: "Titulaire du compte",
  bank: "Banque",
  save: "Enregistrer",
  saved: "Enregistré",
  saveError: "Enregistrement impossible. Réessaie.",
  profileTitle: "Profil",
  language: "Langue",
  legal: "Mentions",
  signOut: "Se déconnecter",
  loadError: "Impossible de charger ton espace. Vérifie ta connexion.",
  retry: "Réessayer",
  actionError: "Ça n’a pas marché. Réessaie.",
};

export function creatorCopy(lang: Lang): Copy {
  return lang === "fr" ? FR : EN;
}

export type CreatorCopy = Copy;
