-- 000052 feature_usage: billable uses of costly features per workspace owner.
--
-- Read by the hourly anti-abuse limits (src/lib/feature-usage.ts): today the
-- Mino site/photo analysis (MINO_ANALYSIS_MAX_PER_HOUR in src/lib/plan-limits.ts).
-- Live creator lookups keep counting in scrape_runs (trigger 'lookup:<owner>').
-- Plans have no monthly quotas; this table only answers "how many in the last hour".
--
-- Server only: RLS on, no policies, no grants to anon/authenticated.
-- Idempotent, and every statement stands on its own (Supabase SQL editor).

create table if not exists public.feature_usage (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  feature text not null check (char_length(feature) between 1 and 64),
  used_at timestamptz not null default now(),
  meta jsonb not null default '{}'::jsonb
);

create index if not exists feature_usage_owner_feature_used_at_idx
  on public.feature_usage (owner_id, feature, used_at desc);

alter table public.feature_usage enable row level security;

revoke all on public.feature_usage from public, anon, authenticated;

grant all on public.feature_usage to service_role;

comment on table public.feature_usage is
  'Billable uses of costly features per workspace owner (hourly anti-abuse limits). Server only.';
